### ISSUE TITLE
AI shipyard cannot work

### ISSUE THREAD

**Issue by liger2** [anno-mods/Spice-it-Up#16]
Hello, first of all, thank you very much for your mod. I downloaded the AI shipyard mod updated 11 days ago and installed the loading file as required, but it didn't work.Thank you very much for your efforts!

**Comment by Serpens66** [comment]
should be fixed by Commit https://github.com/anno-mods/Spice-it-Up/commit/a69f2d50ae9faf7c669268e50adba7567a1d0a38
If this was not yet released as download or at nexus, you can download the whole zip here https://github.com/anno-mods/Spice-it-Up by clicking the green "Code" button and download as zip.
