### ISSUE TITLE
Cant remove trees in New World

### ISSUE THREAD

**Issue by LeonTheCreative07** [anno-mods/Spice-it-Up#26]
After downloading the mod, i decided to use the "Remove Southern Rivers" mod, but now i cant delete some trees, which rly sucks. I also cant cover it with buildings, so the trees will simply be stuck there. Any ideas how to fix or why that happened?

**Comment by taubenangriff** [comment]
It is on one island I presume?

![mapimage](https://user-images.githubusercontent.com/51975164/192150445-3e704863-add6-43ad-b83e-33a4393e8d42.png)

In that case, Ubisoft has had a fuckup in their map exporter. The fix is not exactly trivial, but I will do my best. 
Until that, you will probably have to settle another island.

Sorry for the inconvenience and thank you for reporting.

**Comment by LeonTheCreative07** [comment]
i only tried on one, but using reduce southern rivers and a new savegame worked

**Comment by taubenangriff** [comment]
As Ubisoft has added the riverless versions to Vanilla in GU16, this is either fixed or no longer a spice it up issue.
